#!/usr/bin/env nextflow
// Generated by PipeGuard from a Pipeline-Builder card graph (ADR-0003 — compose ≠ execute:
// PipeGuard emitted this text; it never ran a tool). Edit params in nextflow.config.
nextflow.enable.dsl = 2

include { FASTP } from './modules/fastp.nf'
include { BWA_MEM2_MEM } from './modules/bwa_mem2_mem.nf'
include { SAMTOOLS_MARKDUP } from './modules/samtools_markdup.nf'
include { MOSDEPTH } from './modules/mosdepth.nf'
include { BCFTOOLS_CALL } from './modules/bcftools_call.nf'
include { MULTIQC } from './modules/multiqc.nf'
include { BCFTOOLS_NORM } from './modules/bcftools_norm.nf'

workflow {
    ch_reads = Channel.value([file(params.read1), file(params.read2)])
    ch_panel_bed = Channel.value(file(params.panel_bed))
    ch_reference = Channel.value([file(params.reference), file("${params.reference}.*")])

    FASTP(ch_reads)
    BWA_MEM2_MEM(FASTP.out.fastq, ch_reference)
    SAMTOOLS_MARKDUP(BWA_MEM2_MEM.out.bam)
    MOSDEPTH(SAMTOOLS_MARKDUP.out.bam, ch_panel_bed)
    BCFTOOLS_CALL(SAMTOOLS_MARKDUP.out.bam, ch_reference, ch_panel_bed)
    MULTIQC(FASTP.out.fastp_json, SAMTOOLS_MARKDUP.out.markdup_metrics, MOSDEPTH.out.mosdepth_summary)
    BCFTOOLS_NORM(BCFTOOLS_CALL.out.vcf, ch_reference)
}
